"""add profile banner_url

Revision ID: 68ffd1e9ad10
Revises: 5063b7a8f605
Create Date: 2026-07-22 12:50:25.180439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ffd1e9ad10'
down_revision: Union[str, Sequence[str], None] = '5063b7a8f605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('banner_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'banner_url')
    # ### end Alembic commands ###
